# Convolutional Neural Network (CNN)

### Import TensorFlow

In [1]:
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import time
import pprint
!nvidia-smi

Mon Dec 20 02:33:05 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8    31W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Paper CNN Tensorflow Model

In [2]:
# Setup input as all ones
input_shape = (1, 1, 56, 100) # Batch Size, Input Channels, Rows, Columns
x = tf.ones(input_shape)

# Setup model
model = models.Sequential()

# Convolution Layer 1: 1 Input, 64 Output, Same dimensions
model.add(layers.Conv2D(64, (8, 8), activation='relu', strides=1, padding='same', input_shape=input_shape[1:], kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov1 = model(x)
#print("cov1:", cov1.shape)

# Maxpool 1: 
model.add(layers.MaxPooling2D((2, 2), strides=2, padding='same', data_format='channels_first'))
#maxpool1 = model(x)
#print("maxpool1:", maxpool1.shape)

# Convolution Layer 2: 64 Input, 64 Output, Same dimensions
model.add(layers.Conv2D(64, (4, 4), activation='relu', strides=1, padding='same', kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov2 = model(x)
#print("cov2:", cov2.shape)

# Maxpool 2: 
model.add(layers.MaxPooling2D((2, 2), strides=2, padding='same', data_format='channels_first'))
#maxpool2 = model(x)
#print("maxpool2:", maxpool2.shape)

# Convolution Layer 3: 64 Input, 64 Output, Same dimensions
model.add(layers.Conv2D(64, (2, 2), activation='relu', strides=1, padding='same', kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov3 = model(x)
#print("cov3:", cov3.shape)

# Fully Connection Layers
##model.add(layers.GlobalAveragePooling2D()) # Not use
model.add(layers.Flatten())
model.add(layers.Dense(256, activation='relu', kernel_initializer="ones", bias_initializer="ones"))
model.add(layers.Dense(3, activation='softmax', kernel_initializer="ones", bias_initializer="ones"))
##model.add(layers.Softmax()) # Not use
#model.summary()

# Get timing results
runs = 10
for i in range(0, runs):
  start_time = time.time()
  y = model(x)
  print("--- %s ms for 1 ---" % ((time.time() - start_time)*1000))

# To save to file 
# https://colab.research.google.com/github/d2l-ai/d2l-en-colab/blob/master/chapter_deep-learning-computation/read-write.ipynb

# Print Results
print("Input:")
print(x.shape)
print(x)

print("Output:")
print(y.shape)
#print(tf.shape(y))
tf.print(y, summarize=5)


--- 10600.562572479248 ms for 1 ---
--- 8.234739303588867 ms for 1 ---
--- 14.50490951538086 ms for 1 ---
--- 5.494832992553711 ms for 1 ---
--- 5.785226821899414 ms for 1 ---
--- 14.641046524047852 ms for 1 ---
--- 13.381719589233398 ms for 1 ---
--- 12.346029281616211 ms for 1 ---
--- 6.774187088012695 ms for 1 ---
--- 6.399631500244141 ms for 1 ---
Input:
(1, 1, 56, 100)
tf.Tensor(
[[[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]], shape=(1, 1, 56, 100), dtype=float32)
Output:
(1, 3)
[[0.333333343 0.333333343 0.333333343]]


Get Model Timing Results when Batching instead of looping

In [3]:
# Setup input as all ones
input_shape = (100, 1, 56, 100) # Batch Size, Input Channels, Rows, Columns
x = tf.ones(input_shape)

# Setup model
model_batch = models.Sequential()

# Convolution Layer 1: 1 Input, 64 Output, Same dimensions
model_batch.add(layers.Conv2D(64, (8, 8), activation='relu', strides=1, padding='same', input_shape=input_shape[1:], kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov1 = model_batch(x)
#print("cov1:", cov1.shape)

# Maxpool 1: 
model_batch.add(layers.MaxPooling2D((2, 2), strides=2, padding='same', data_format='channels_first'))
#maxpool1 = model_batch(x)
#print("maxpool1:", maxpool1.shape)

# Convolution Layer 2: 64 Input, 64 Output, Same dimensions
model_batch.add(layers.Conv2D(64, (4, 4), activation='relu', strides=1, padding='same', kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov2 = model_batch(x)
#print("cov2:", cov2.shape)

# Maxpool 2: 
model_batch.add(layers.MaxPooling2D((2, 2), strides=2, padding='same', data_format='channels_first'))
#maxpool2 = model_batch(x)
#print("maxpool2:", maxpool2.shape)

# Convolution Layer 3: 64 Input, 64 Output, Same dimensions
model_batch.add(layers.Conv2D(64, (2, 2), activation='relu', strides=1, padding='same', kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov3 = model_batch(x)
#print("cov3:", cov3.shape)

# Fully Connection Layers
##model_batch.add(layers.GlobalAveragePooling2D()) # Not use
model_batch.add(layers.Flatten())
model_batch.add(layers.Dense(256, activation='relu', kernel_initializer="ones", bias_initializer="ones"))
model_batch.add(layers.Dense(3, activation='softmax', kernel_initializer="ones", bias_initializer="ones"))
##model_batch.add(layers.Softmax()) # Not use
#model_batch.summary()

# Get timing results
runs = 10
for i in range(0, runs):
  start_time = time.time()
  y = model_batch(x)
  print("--- %s ms for 1 ---" % ((time.time() - start_time)*1000))

# To save to file 
# https://colab.research.google.com/github/d2l-ai/d2l-en-colab/blob/master/chapter_deep-learning-computation/read-write.ipynb

# Print Results
print("Input:")
print(x.shape)
print(x)

print("Output:")
print(y.shape)
#print(tf.shape(y))
tf.print(y, summarize=5)

--- 332.841157913208 ms for 1 ---
--- 4.761934280395508 ms for 1 ---
--- 4.318952560424805 ms for 1 ---
--- 4.299640655517578 ms for 1 ---
--- 4.454374313354492 ms for 1 ---
--- 4.554271697998047 ms for 1 ---
--- 4.196643829345703 ms for 1 ---
--- 4.244565963745117 ms for 1 ---
--- 4.448890686035156 ms for 1 ---
--- 4.433631896972656 ms for 1 ---
Input:
(100, 1, 56, 100)
tf.Tensor(
[[[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]


 [[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]


 [[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]


 ...


 [[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
 

Try Model but with MaxPool Stride=1

In [4]:
# Setup input as all ones
input_shape = (1, 1, 56, 100) # Batch Size, Input Channels, Rows, Columns
x = tf.ones(input_shape)

# Setup model
model_maxpool_stride1 = models.Sequential()

# Convolution Layer 1: 1 Input, 64 Output, Same dimensions
model_maxpool_stride1.add(layers.Conv2D(64, (8, 8), activation='relu', strides=1, padding='same', input_shape=input_shape[1:], kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov1 = model_maxpool_stride1(x)
#print("cov1:", cov1.shape)

# Maxpool 1: 
model_maxpool_stride1.add(layers.MaxPooling2D((2, 2), strides=1, padding='same', data_format='channels_first'))
#maxpool1 = model_maxpool_stride1(x)
#print("maxpool1:", maxpool1.shape)

# Convolution Layer 2: 64 Input, 64 Output, Same dimensions
model_maxpool_stride1.add(layers.Conv2D(64, (4, 4), activation='relu', strides=1, padding='same', kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov2 = model_maxpool_stride1(x)
#print("cov2:", cov2.shape)

# Maxpool 2: 
model_maxpool_stride1.add(layers.MaxPooling2D((2, 2), strides=1, padding='same', data_format='channels_first'))
#maxpool2 = model_maxpool_stride1(x)
#print("maxpool2:", maxpool2.shape)

# Convolution Layer 3: 64 Input, 64 Output, Same dimensions
model_maxpool_stride1.add(layers.Conv2D(64, (2, 2), activation='relu', strides=1, padding='same', kernel_initializer="ones", bias_initializer="ones", data_format='channels_first'))
#cov3 = model_maxpool_stride1(x)
#print("cov3:", cov3.shape)

# Fully Connection Layers
##model_maxpool_stride1.add(layers.GlobalAveragePooling2D()) # Not use
model_maxpool_stride1.add(layers.Flatten())
model_maxpool_stride1.add(layers.Dense(256, activation='relu', kernel_initializer="ones", bias_initializer="ones"))
model_maxpool_stride1.add(layers.Dense(3, activation='softmax', kernel_initializer="ones", bias_initializer="ones"))
##model_maxpool_stride1.add(layers.Softmax()) # Not use
#model_maxpool_stride1.summary()

# Get timing results
runs = 10
for i in range(0, runs):
  start_time = time.time()
  y = model_maxpool_stride1(x)
  print("--- %s ms for 1 ---" % ((time.time() - start_time)*1000))

# To save to file 
# https://colab.research.google.com/github/d2l-ai/d2l-en-colab/blob/master/chapter_deep-learning-computation/read-write.ipynb

# Print Results
print("Input:")
print(x.shape)
print(x)

print("Output:")
print(y.shape)
#print(tf.shape(y))
tf.print(y, summarize=5)

--- 80.28817176818848 ms for 1 ---
--- 5.268335342407227 ms for 1 ---
--- 4.271984100341797 ms for 1 ---
--- 4.853487014770508 ms for 1 ---
--- 4.602670669555664 ms for 1 ---
--- 4.489898681640625 ms for 1 ---
--- 4.712343215942383 ms for 1 ---
--- 4.301786422729492 ms for 1 ---
--- 4.383563995361328 ms for 1 ---
--- 4.228830337524414 ms for 1 ---
Input:
(1, 1, 56, 100)
tf.Tensor(
[[[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]], shape=(1, 1, 56, 100), dtype=float32)
Output:
(1, 3)
[[0.333333343 0.333333343 0.333333343]]


Try with random weight values to see if the fast times from above tests is due to some caching

In [5]:
# Setup input as all ones
input_shape = (1, 1, 56, 100) # Batch Size, Input Channels, Rows, Columns
x = tf.ones(input_shape)

init_val = "RandomUniform"

# Setup model
model_rand = models.Sequential()

# Convolution Layer 1: 1 Input, 64 Output, Same dimensions
model_rand.add(layers.Conv2D(64, (8, 8), activation='relu', strides=1, padding='same', input_shape=input_shape[1:], kernel_initializer=init_val, bias_initializer=init_val, data_format='channels_first'))
#cov1 = model_rand(x)
#print("cov1:", cov1.shape)

# Maxpool 1: 
model_rand.add(layers.MaxPooling2D((2, 2), strides=1, padding='same', data_format='channels_first'))
#maxpool1 = model_rand(x)
#print("maxpool1:", maxpool1.shape)

# Convolution Layer 2: 64 Input, 64 Output, Same dimensions
model_rand.add(layers.Conv2D(64, (4, 4), activation='relu', strides=1, padding='same', kernel_initializer=init_val, bias_initializer=init_val, data_format='channels_first'))
#cov2 = model_rand(x)
#print("cov2:", cov2.shape)

# Maxpool 2: 
model_rand.add(layers.MaxPooling2D((2, 2), strides=1, padding='same', data_format='channels_first'))
#maxpool2 = model_rand(x)
#print("maxpool2:", maxpool2.shape)

# Convolution Layer 3: 64 Input, 64 Output, Same dimensions
model_rand.add(layers.Conv2D(64, (2, 2), activation='relu', strides=1, padding='same', kernel_initializer=init_val, bias_initializer=init_val, data_format='channels_first'))
#cov3 = model_rand(x)
#print("cov3:", cov3.shape)

# Fully Connection Layers
##model_rand.add(layers.GlobalAveragePooling2D()) # Not use
model_rand.add(layers.Flatten())
model_rand.add(layers.Dense(256, activation='relu', kernel_initializer=init_val, bias_initializer=init_val))
model_rand.add(layers.Dense(3, activation='softmax', kernel_initializer=init_val, bias_initializer=init_val))
##model_rand.add(layers.Softmax()) # Not use
#model_rand.summary()

# Get timing results
runs = 10
for i in range(0, runs):
  start_time = time.time()
  y = model_rand(x)
  print("--- %s ms for 1 ---" % ((time.time() - start_time)*1000))

# To save to file 
# https://colab.research.google.com/github/d2l-ai/d2l-en-colab/blob/master/chapter_deep-learning-computation/read-write.ipynb

# Print Results
print("Input:")
print(x.shape)
print(x)

print("Output:")
print(y.shape)
#print(tf.shape(y))
tf.print(y, summarize=5)

--- 4.449129104614258 ms for 1 ---
--- 4.121065139770508 ms for 1 ---
--- 4.470586776733398 ms for 1 ---
--- 4.921436309814453 ms for 1 ---
--- 5.092144012451172 ms for 1 ---
--- 4.525661468505859 ms for 1 ---
--- 4.509687423706055 ms for 1 ---
--- 4.578351974487305 ms for 1 ---
--- 5.162715911865234 ms for 1 ---
--- 4.436492919921875 ms for 1 ---
Input:
(1, 1, 56, 100)
tf.Tensor(
[[[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]], shape=(1, 1, 56, 100), dtype=float32)
Output:
(1, 3)
[[0.292113513 0.263940901 0.443945616]]


Now Try with objax

In [ ]:
#Install Objax
!pip --quiet install  objax
import objax
import tensorflow as tf 
import tensorflow_datasets as tfds
import numpy as np
import jax.numpy as jn
import random 
import matplotlib.pyplot as plt
from pprint import  pprint
from tensorflow.keras import datasets, layers, models


In [ ]:
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

X_train = train_images.transpose(0, 3, 1, 2) / 255.0
Y_train = train_labels.flatten()
X_test = test_images.transpose(0, 3, 1, 2) / 255.0
Y_test = test_labels.flatten()

In [ ]:
class ConvNet(objax.Module):
  def __init__(self, number_of_channels = 3, number_of_classes = 10):
    self.conv_1 = objax.nn.Sequential([objax.nn.Conv2D(number_of_channels, 32, 3, padding="VALID"), objax.functional.relu])
    self.conv_2 = objax.nn.Sequential([objax.nn.Conv2D(32, 64, 3, padding="VALID"), objax.functional.relu])
    self.conv_3 = objax.nn.Sequential([objax.nn.Conv2D(64, 64, 3, padding="VALID"), objax.functional.relu])

    self.linear1 = objax.nn.Sequential([objax.nn.Linear(1024, 64), objax.functional.relu])
    self.linear2 = objax.nn.Linear(64, number_of_classes)

  def __call__(self, x):
    #print(x.shape)
    x = objax.functional.max_pool_2d(self.conv_1(x), 2)
    #print(x.shape)
    x = objax.functional.max_pool_2d(self.conv_2(x), 2)
    #print(x.shape)
    x = self.conv_3(x)
    #print(x.shape)
    x = objax.functional.flatten(x)
    #print(x.shape)
    x = self.linear1(x)
    #print(x.shape)
    x = self.linear2(x)
    #print(x.shape)
    return x

#The following line creates the CNN
model = ConvNet()
#You can examine the architecture of our CNN by calling model.vars()
print(model.vars())

(ConvNet).conv_1(Sequential)[0](Conv2D).b        32 (32, 1, 1)
(ConvNet).conv_1(Sequential)[0](Conv2D).w       864 (3, 3, 3, 32)
(ConvNet).conv_2(Sequential)[0](Conv2D).b        64 (64, 1, 1)
(ConvNet).conv_2(Sequential)[0](Conv2D).w     18432 (3, 3, 32, 64)
(ConvNet).conv_3(Sequential)[0](Conv2D).b        64 (64, 1, 1)
(ConvNet).conv_3(Sequential)[0](Conv2D).w     36864 (3, 3, 64, 64)
(ConvNet).linear1(Sequential)[0](Linear).b       64 (64,)
(ConvNet).linear1(Sequential)[0](Linear).w    65536 (1024, 64)
(ConvNet).linear2(Linear).b                      10 (10,)
(ConvNet).linear2(Linear).w                     640 (64, 10)
+Total(10)                                   122570


In [ ]:
#Define loss function as averaged value of of cross entropies
def loss_function(x, labels):
    logit = model(x)
    return objax.functional.loss.cross_entropy_logits_sparse(logit, labels).mean()

#Define a prediction function
predict = objax.Jit(lambda x: objax.functional.softmax(model(x)), model.vars()) 

#Create an object that can be used to calculate the gradient and value of loss_function
gv= objax.GradValues(loss_function, model.vars())

#Create an object that can be used to provide trainable variables in the model
tv = objax.ModuleList(objax.TrainRef(x) for x in model.vars().subset(objax.TrainVar))

opt = objax.optimizer.Adam(model.vars())

#Training routine
def train_op(x, y, learning_rate):
    lr = learning_rate
    gradient, loss_value = gv(x, y)   # calculate gradient and loss value "backprop"
    for grad, params in zip(gradient, tv.vars()):
      params.value -= lr * grad
    #opt(lr, gradient)  # update weights
    return loss_value                      # return loss value

#make train_op (much) faster using JIT compilation
train_op = objax.Jit(train_op, gv.vars() + tv.vars())

In [ ]:
def train(EPOCHS = 10, BATCH = 32, LEARNING_RATE = 9e-4):
  avg_train_loss_epoch = []
  train_acc_epoch = []

  for epoch in range(EPOCHS):
      avg_train_loss = 0 # (averaged) training loss per batch
      train_acc = 0      # training accuracy per batch

      # shuffle the examples prior to training to remove correlation 
      train_indices = np.arange(len(X_train)) 
      #np.random.shuffle(train_indices)
      for it in range(0, X_train.shape[0], BATCH):
          #print("{}:{}".format(it, it + BATCH))
          batch = train_indices[it : it + BATCH] #PUT YOUR CODE HERE#
          #print(X_train[batch])
          #print(len(batch))
          avg_train_loss += float(train_op(X_train[batch], Y_train[batch], LEARNING_RATE)[0]) * len(batch)
          train_prediction = predict(X_train[batch]).argmax(1)
          train_acc += (np.array(train_prediction).flatten() == Y_train[batch]).sum()
      train_acc_epoch.append(train_acc/X_train.shape[0])
      avg_train_loss_epoch.append(avg_train_loss/X_train.shape[0])
      print('Epoch %04d Training Loss %.2f Training Accuracy %.2f' % (epoch + 1, avg_train_loss/X_train.shape[0], 100*train_acc/X_train.shape[0]))

  #Plot training loss
  plt.title("Train Loss")
  plt.plot(avg_train_loss_epoch, label="Train")
  plt.xlabel("Epoch")
  plt.ylabel("Loss")
  plt.legend(loc='best')
  plt.show()

  plt.title("Train")
  plt.plot(train_acc_epoch, label="Train")
  plt.xlabel("Epoch")
  plt.ylabel("Accuracy (%)")
  plt.legend(loc='best')
  plt.show()

In [ ]:
def test(BATCH = 32):
  avg_test_loss = 0 # (averaged) test loss per batch
  test_acc = 0      # test accuracy per batch

  # run test set
  test_indices = np.arange(len(X_test)) 
  #np.random.shuffle(test_indices)    
  for it in range(0, X_test.shape[0], BATCH):
      batch = test_indices[it : it + BATCH] #PUT YOUR CODE HERE#
      avg_test_loss += float(loss_function(X_test[batch], Y_test[batch])) * len(batch)
      test_prediction = predict(X_test[batch]).argmax(1)
      test_acc += (np.array(test_prediction).flatten() == Y_test[batch]).sum()
  test_acc = (test_acc/X_test.shape[0])
  avg_test_loss = (avg_test_loss/X_test.shape[0])

  print('Test Loss %.2f Test Accuracy %.2f' % (avg_test_loss, 100*test_acc))

In [ ]:
train()

Epoch 0001 Training Loss 2.30 Training Accuracy 13.63
Epoch 0002 Training Loss 2.30 Training Accuracy 13.68
Epoch 0003 Training Loss 2.30 Training Accuracy 13.67
Epoch 0004 Training Loss 2.30 Training Accuracy 13.68
Epoch 0005 Training Loss 2.30 Training Accuracy 13.68


KeyboardInterrupt: ignored

In [ ]:
test()

Extra Debug Stuff - Can Ignore

In [ ]:
# With `padding` as "same".
input_shape = (1, 4, 5, 1)
x = tf.ones(input_shape)
model = tf.keras.layers.Conv2D(1, 2, padding="same", input_shape=input_shape, kernel_initializer="ones", bias_initializer="zeros")
y = model(x)

print("Input:")
pprint.pprint(x)
print("Output:")
pprint.pprint(y)

print("Weights:")
print(model.get_config(), model.get_weights())
weights = model.get_weights()
pprint.pprint(weights)

#input = tf.ones((5, 4), dtype=tf.float32)
#kernel = tf.ones((2, 2), dtype=tf.float32)
#print(input)
#conv = tf.nn.conv2d(input, kernel, 1, 'SAME')
#print(conv)

KeyboardInterrupt: ignored

In [ ]:
# With `padding` as "same".
input_shape = (1, 56, 100, 1)
x = tf.ones(input_shape)
model = tf.keras.layers.Conv2D(1, 2, padding="same", input_shape=input_shape[1:], kernel_initializer="ones", bias_initializer="zeros")
y = model(x)

print("Input:")
pprint.pprint(x)
print("Output:")
pprint.pprint(y)

print("Weights:")
print(model.get_config(), model.get_weights())
weights = model.get_weights()
pprint.pprint(weights)

When starting with new runtime: 
27.790482997894287 seconds for 1

Second time running:
0.00956869125366211 seconds

Third time:
0.005471467971801758 seconds

0.009866952896118164 seconds 
0.00510859489440918 seconds

In [5]:
input_shape = (1, 1, 4, 2)
x = tf.ones(input_shape)
print(x)

tf.Tensor(
[[[[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]]], shape=(1, 1, 4, 2), dtype=float32)
